#!/bin/sh

DEFAULT_PORT=60999
EXE_DIR=$(cd "$(dirname "$0")" && pwd)
SITE_BASE=$(cd "$1" && pwd)
[ -z "$SITE_BASE" ] && SITE_BASE=$(cd "$(dirname "$0")" && pwd)

CONFIG="$SITE_BASE/.lighttpd.conf"
TEMPLATE="$EXE_DIR/lighttpd.conf.template"

PORT=$2
[ -z "$PORT" ] && PORT=$(cat "$SITE_BASE/.lighttpd.port" 2>/dev/null)
[ -z "$PORT" ] && PORT=$(cat "$SITE_BASE/.port" 2>/dev/null)
[ -z "$PORT" ] && PORT=$DEFAULT_PORT

echo "Serving on port $PORT in $SITE_BASE."
#[ "$PORT" = "$DEFAULT_PORT" ] && echo "WARNING: Using the default port, please configure a different one!"
sed "s|{{SITE_BASE}}|$SITE_BASE|;s|{{PORT}}|$PORT|" "$TEMPLATE" > "$CONFIG"
/usr/sbin/lighttpd -D -f "$CONFIG"

