#!/bin/sh

if [ ! -d "build" ]; then
  echo "Can't find build directory, did you 'npm install' and 'npm run build'?" >/dev/stderr
  exit 255
fi

[ ! -e build/chromattis ] && (cd build && ln -fs . chromattis)

DEFAULT_PORT=60999
LIGHTTPD_DIR=$(cd "$(dirname "$0")" && pwd)
SITE_BASE="$(cd "$LIGHTTPD_DIR/.." && pwd)"

CONFIG="$LIGHTTPD_DIR/.lighttpd.conf"
TEMPLATE="$LIGHTTPD_DIR/lighttpd.conf.template"

PORT=$1
[ -z "$PORT" ] && PORT=$(cat "$LIGHTTPD_DIR/.lighttpd.port" 2>/dev/null)
[ -z "$PORT" ] && PORT=$(cat "$LIGHTTPD_DIR/.port" 2>/dev/null)
[ -z "$PORT" ] && PORT=$DEFAULT_PORT

echo "Serving on port $PORT in $SITE_BASE/build"
#[ "$PORT" = "$DEFAULT_PORT" ] && echo "WARNING: Using the default port, please configure a different one!"
sed "s|{{SITE_BASE}}|$SITE_BASE|;s|{{PORT}}|$PORT|" "$TEMPLATE" > "$CONFIG"
/usr/sbin/lighttpd -D -f "$CONFIG"

